# Generated by Django 5.0.3 on 2024-11-07 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipemodel',
            old_name='image',
            new_name='images',
        ),
    ]
