# Generated by Django 5.0.3 on 2024-11-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_rename_image_recipemodel_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='ingrediance',
            field=models.TextField(max_length=300),
        ),
    ]
