# Generated by Django 5.0.3 on 2024-11-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_recipemodel_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='images',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
