# Generated by Django 5.0.3 on 2024-11-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_alter_recipemodel_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='description',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='ingrediance',
            field=models.TextField(max_length=3000),
        ),
    ]
